
services:
  elastic:
    image: blankhang/elasticsearch:${ELK_VERSION}
    #restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    deploy:
      resources:
        limits:
          #cpus: '1'
          memory: 1G
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    volumes:
      - ./data-elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: kibana:${ELK_VERSION}
    #restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}

    volumes:
      - ./data-kibana:/usr/share/kibana/data
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml